Feature v1.0.1 entity repository
711skhu/core pull request #7
Opened 2019-04-07 05:55 UTC by yjll1019

+ TestCase 생성자 코드 추가.
+ entity 테스트 코드 작성.
했습니다.

2019-04-07 06:14 UTC, songz1 approved these changes

2019-04-07 08:27 UTC, shouwn requested changes

2019-04-07 08:27 UTC, shouwn commented on src/test/java/com/shouwn/oj/repository/problem/ProblemDetailRepositoryTest.java
> +				.build();
현재 기능 정의에 문제 생성 시 바로 startDate와 endDate가 생기는 것이 아니기 때문에
Problem Builder 생성자에서 startDate와 endDate를 빼는 게 좋아 보이네요.

2019-04-07 08:27 UTC, shouwn commented on src/test/java/com/shouwn/oj/repository/problem/ProblemDetailRepositoryTest.java
> +				.build();
추가로 LocalDateTime은

LocalDateTime.of(2015, 4, 17, 23, 23, 50); // 2015년4월17일23시23분50초 
Year.of(2015).atMonth(3).atDay(4).atTime(10, 30); // 2015년3월4일 10시30분00초

이렇게도 만들 수 있으니 참고하면 좋을 것 같아요.

2019-04-07 08:27 UTC, shouwn commented on src/test/java/com/shouwn/oj/repository/member/AdminRepositoryTest.java
> +				.build();
현재 IDE 설정으로 인해서 들여쓰기가 이렇게 된 건가요?

인텔리J에서 파일 전체 선택 후 ctrl + alt + l 을 사용해보셨나요?

2019-04-07 08:30 UTC, shouwn commented
PR의 제목은 브랜치 제목 보다는 무엇을 한 것인지 적어주시는 게 좋다고 생각해요

2019-04-09 06:49 UTC, yjll1019 commented on src/test/java/com/shouwn/oj/repository/problem/ProblemDetailRepositoryTest.java
> +				.build();
네~ 감사합니다. 생성자 수정해서 커밋하겠습니다!

2019-04-09 06:51 UTC, yjll1019 commented on src/test/java/com/shouwn/oj/repository/member/AdminRepositoryTest.java
> +				.build();
네..

2019-04-09 06:56 UTC, kje6445 approved these changes

2019-04-09 07:22 UTC, 1eehyeji requested changes

2019-04-09 07:22 UTC, lwiiiiii commented on src/main/java/com/shouwn/oj/model/entity/member/Member.java
> +public abstract class Member extends BaseEntity {
사용자 인증 구현을 위해 getRole()메소드가 필요합니당! 부탁드려욥 😊

2019-04-09 07:23 UTC, yjll1019 commented on src/main/java/com/shouwn/oj/model/entity/member/Member.java
> +public abstract class Member extends BaseEntity {
네~!

2019-04-09 08:18 UTC, 1eehyeji approved these changes

2019-04-09 08:20 UTC, KimJye approved these changes

2019-04-09 10:37 UTC, shouwn commented on src/test/java/com/shouwn/oj/repository/member/AdminRepositoryTest.java
> +				.build();
저도 위에 처럼 나오네요. ㅠㅠ

2019-04-09 10:38 UTC, shouwn approved these changes

2019-04-09 10:44 UTC, 1eehyeji approved these changes

2019-04-09 15:28 UTC, merged