service class 작성
711skhu/core pull request #8
Opened 2019-04-09 10:00 UTC by lwiiiiii

2019-04-09 10:02 UTC, KimJye approved these changes

2019-04-09 10:43 UTC, yjll1019 approved these changes

2019-04-09 14:07 UTC, shouwn approved these changes

2019-04-09 14:08 UTC, shouwn requested changes
패키지명은 동일한 형식을 맞추기 위해 현재 entity 작성 브랜치에서 entity 패키지와 같이 
service - memember
service - problem
으로 해주세요

2019-04-10 05:07 UTC, shouwn approved these changes

2019-04-10 05:19 UTC, shouwn commented
현재는 이렇게 해놓고 나중에 loadUserByUsername에서 Username으로 유저를 검색하는 부분을 MemberRepository에서 할지 StudentRepository에서 할지 정하면 될 것 같네요.

MemberReporisory에서 하면 MemberService에서 loadUserByUsername 메소드를 오버라이드하고
자식에서 한다면 자식에서 loadUserByUsername 메소드를 오버라이드 하는 방식으로요.

2019-04-10 06:01 UTC, songz1 approved these changes

2019-04-14 00:50 UTC, merged