JwtProvider, MemberPrincipal class 구현
711skhu/core pull request #9
Opened 2019-04-15 12:02 UTC by lwiiiiii

2019-04-15 12:28 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +	private Logger logger = LoggerFactory.getLogger(JwtProvider.class);
클래스에 @slf4j를 사용하면 쉽게 log 객체를 얻을 수 있습니다. 참고하면 좋을 것 같아요

2019-04-15 12:30 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +				.setSubject(memberPrincipal.getUsername())
id가 아니고 username을 토큰에 저장하는 이유가 무엇인가요?

2019-04-15 12:40 UTC, shouwn requested changes

2019-04-15 12:40 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +		MemberPrincipal memberPrincipal = (MemberPrincipal) authentication.getPrincipal();
매개변수로 Authentication 클래스를 사용하면 Jwt가 Spring Secutiry에 종속되기 때문에 
매개변수로 username을 사용할 거라면 String, id를 사용할 거라면 Long을 사용하는 게 좋아 보입니다.

2019-04-15 12:40 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +		return false;
getUsernameFromJwt와 validateJwt의 경우 둘 다 내부에 parse를 하는 메소드이고 결국 원하는 것은 claim 이기 때문에 두 메소드를 합쳐서 get ~~ 메소드를 만드는 건 어떤가요?

2019-04-15 12:40 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/MemberPrincipal.java
> +public class MemberPrincipal implements UserDetails {
MemberPrincipal을 안 만들고 Member 클래스가 UserDetails를 상속하는 건 어떤가요?

2019-04-15 12:40 UTC, shouwn commented on src/test/java/com/shouwn/oj/security/JwtProviderTest.java
> +	}
실패 테스트도 좋지만 성공 테스트도 있으면 더 좋겠네요. 추가로 jwt에 저장된 값을 제대로 얻을 수 있는지도 테스트하면 좋을 것 같습니다.

2019-04-15 13:30 UTC, lwiiiiii commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +				.setSubject(memberPrincipal.getUsername())
로그인 시에 username 값을 사용자에게 받아오기 때문에 username으로 했습니다! id값을 저장하는게 앞으로 코드 구현할 때 편리할까요??

2019-04-15 13:37 UTC, shouwn commented on src/main/java/com/shouwn/oj/security/JwtProvider.java
> +				.setSubject(memberPrincipal.getUsername())
username과 password을 받는 것은 이 유저에게 토큰을 발급해도 괜찮은지 확인하기 위해서 입니다.

저희가 발급한 토큰으로 인증 시에 jwt는 저희가 발급했다는 확증이 있기 때문에 jwt를 믿고 사용할 수 있습니다. (이 부분은 jwt 구성을 찾아 보면 좋을 것 같아요. jwt안에 저희가 넣은 값은 누구나 볼 수 있기 때문에 비밀번호와 같은 것은 절대 들어가면 안 됩니다. jwt는 세 부분으로 구성되어 있는데 이걸 찾아보고 이슈에 기술 공유로 적어주시면 좋을 것 같아요.^^ )

인증한 뒤에 저희가 유저를 조회할 때 id가 더 편리하고 더 빠르게 찾을 수 있기 때문에 저는 id를 넣는 게 더 좋을 것 같아요.

2019-04-15 15:18 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/entity/member/Member.java
> +	}
어떤 이유로 private Member 생성자를 만드신 건가요?

+ authorities의 경우 UserDetail의 getter를 구현하기 위함인데 이 부분은 getAuthorities() 메소드 안에서 getRole() 메소드로 충분히 구현 가능할 것 같습니다.

2019-04-17 01:54 UTC, songz1 approved these changes

2019-04-17 14:13 UTC, shouwn requested changes

2019-04-17 14:13 UTC, shouwn commented on src/test/java/com/shouwn/oj/security/JwtProviderTest.java
> +	@Test(expected = JwtException.class)
Junit5 가 기본 설정인데 테스트가 성공하나요?

패키지 주소를 보면 org.junit.Test 는 Junit4의 패키지 명이고
org.junit.jupiter로 시작하는 것이 Junit5의 패키지 명입니다.

현재 Test 어노테이션은 Junit4 걸로 되어 있네요.

2019-04-18 04:14 UTC, shouwn approved these changes

2019-04-18 05:57 UTC, songz1 approved these changes

2019-04-18 13:51 UTC, KimJye approved these changes

2019-04-18 13:55 UTC, yjll1019 approved these changes

2019-04-18 13:57 UTC, merged